language: node_js
node_js:
  - "4.2"
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
  - SAUCE_USERNAME=aidaskk
  - SAUCE_ACCESS_KEY=6e96b47e-6665-4f69-beaa-085e5d5b6b9b
addons:
  sauce_connect: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install
script:
  - grunt karma:coverage
  - grunt karma:saucelabs || true
